config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'order_details/update'
  end
  namespace :admin do
   resources :orders, only: [:show, :update]
  end
  namespace :admin do
   resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end
  namespace :admin do
    resources :items, except: [:destroy, :update, :create]
    patch 'items/:id' => 'items#update', as: 'update_item'
    post 'items/new' => 'items#create'
  end
  namespace :admin do
   patch 'order_detail/:id' => 'order_detail#update'
  end

  namespace :admin do
   root to: "homes#top"
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }




  devise_scope :public do
    root to: "public/homes#top"
    get 'about' => 'public/homes#about', as: 'about'
    resources :addresses, only: [:index, :edit, :create, :destroy], module: 'public'
    patch 'addresses/:id/edit' => 'public/addresses#update'
    get 'orders/complete' => 'public/orders#complete'
    resources :orders, only: [:new, :index, :create, :show], module: 'public'
    post 'orders/confirm' => 'public/orders#confirm'
    delete 'cart_items' => 'public/cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create, :destroy_all], module: 'public'
    resources :items, only: [:index, :show], module: 'public'
    get 'customers/show' => 'public/customers#show'
    get 'customers/edit' => 'public/customers#edit'
    patch 'customers' => 'public/customers#update'
    get 'customers/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'
  end

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations", only: [:new, :create],
  sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def add_address
    "〒" + self.postal_code + " "  + self.address + "　" + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  

  def active_for_authentication?
     super && (is_deleted == false)
  end
  
  def name
    self.last_name + self.first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  # has_many :customer, through: :cart_items
  # has_many :orders, through: :order_details
  belongs_to :genre

  def add_tax_price
      (price * 1.10).floor
      # 税込価格
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  # has_many :items, through: :order_details
  enum payment_method: { credit_card: 0, transfer: 1}
 # enum status: { waiting: 0, confirmation: 1, production: 2, preparation: 3, send: 4}


  def sum_price
      item.add_tax_price * order_details.amount
  end

  def delivery_address
      "〒" + self.postal_code + "　" + self.address + "　" + self.name
  end




end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

   def total_price
    item.add_tax_price * amount
    # 小計
   end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).per(20)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path
  end

  def show
    @customer = Customer.find(params[:id])
  end

  private
  def customer_params
    params.require(:customer).permit(:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(20)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
   before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end


  def create
   @item = Item.new(item_params)
   @item.save
   redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end




  private
  def item_params
   params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
end

app/controllers/amin/orders_controller.rb
class Amin::OrdersController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address ,:telephone_number])
   end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/amin/orders_helper.rb
module Amin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container px-2 px-sm-0">
    <h5 class="col-3 text-center" style="background-color: #ddd;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h5>
<div class="row">
<div class="col-10">
  <%= form_with model: @customer, url: admin_customer_path, method: :patch, local: true do |f| %>

    <label class="col-md-3">会員ID</label>
    <%= @customer.id %></br>


    <label class="col-md-3">氏名</label>
    <%= f.text_field :last_name%>
    <%= f.text_field :first_name%></br>


    <label class="col-md-3">フリガナ</label>
    <%= f.text_field :last_name_kana %>
    <%= f.text_field :first_name_kana %></br>

    <label class="col-md-3">郵便番号</label>
    <%= f.number_field :postal_code %></br>

    <label class="col-md-3">住所</label>
    <%= f.text_field :address %></br>

    <label class="col-md-3">電話番号</label>
    <%= f.phone_field :telephone_number%></br>

    <label class="col-md-3">メールアドレス</label>
    <%= f.email_field :email %></br>

    <label class="col-md-3">会員ステータス</label>
     　<%= f.radio_button :is_deleted, :false %>
      <%= f.label :is_deleted, "有効" %>
      <%= f.radio_button :is_deleted, :true %>
      <%= f.label :is_deleted, "退会" %></br>

     <label class="col-md-3"></label>
     <%= f.submit '変更を保存', class:"btn btn-success px-5" %>

  <% end %>
</div>
</div>
</div>

app/views/admin/customers/index.html.erb
<div class="container px-2 px-sm-0">
<h5 class="col-2 text-center mb-5 ml-5" style="background-color: #ddd;">会員一覧</h5>
    <div class="row">
      <div class="col-8 mx-auto">
  <table class="table">
  <thead class="table-secondary">
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= link_to admin_customer_path(customer.id) do %><%= customer.last_name %><%= customer.first_name %><% end %></td>
      <td><%= customer.email %></td>
      <td><% if customer.is_deleted == false %><span class="text-success font-weight-bold">有効</span>
          <% else %><span class="text-secondary font-weight-bold">退会</span>
          <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
  </div>
</div>
<div class="col-1 mx-auto">
<%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container pt-3 px-sm-0">

    <h5 class="col-3 text-center mb-5 ml-5" style="background-color: #ddd;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h5>

  <div class="row mx-5">
  <div class="col-10">
   <label class="col-md-3">会員ID</label><%= @customer.id %></br>
   <label class="col-md-3">氏名</label><%= @customer.last_name %> <%= @customer.first_name %></br>
   <label class="col-md-3">フリガナ</label><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></br>
   <label class="col-md-3">郵便番号</label><%= @customer.postal_code %></br>
   <label class="col-md-3">住所</label><%= @customer.address %></br>
   <label class="col-md-3">電話番号</label><%= @customer.telephone_number %></br>
   <label class="col-md-3">メールアドレス</label><%= @customer.email %></br>
   <label class="col-md-3">会員ステータス</label>
          <% if @customer.is_deleted == false %><span class="text-success font-weight-bold">有効</span>
          <% else %><span class="text-secondary font-weight-bold">退会</span>
          <% end %></br>
  <label class="col-md-3"></label>
  <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success mr-5" %>
  <%= link_to "注文履歴一覧を見る", admin_root_path, class:"btn btn-primary" %>
  </div>
  </div>

</div>