config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'order_details/update'
  end
  namespace :admin do
   resources :orders, only: [:show, :update]
  end
  namespace :admin do
   resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end
  namespace :admin do
    resources :items, except: [:destroy, :update, :create]
    patch 'items/:id' => 'items#update', as: 'update_item'
    post 'items/new' => 'items#create'
  end
  namespace :admin do
   patch 'order_detail/:id' => 'order_detail#update'
  end

  namespace :admin do
   root to: "homes#top"
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }




  devise_scope :public do
    root to: "public/homes#top"
    get 'about' => 'public/homes#about', as: 'about'
    resources :addresses, only: [:index, :edit, :create, :destroy], module: 'public'
    patch 'addresses/:id/edit' => 'public/addresses#update'
    get 'orders/complete' => 'public/orders#complete'
    resources :orders, only: [:new, :index, :create, :show], module: 'public'
    post 'orders/confirm' => 'public/orders#confirm'
    delete 'cart_items' => 'public/cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create, :destroy_all], module: 'public'
    resources :items, only: [:index, :show], module: 'public'
    get 'customers/show' => 'public/customers#show'
    get 'customers/edit' => 'public/customers#edit'
    patch 'customers' => 'public/customers#update'
    get 'customers/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'
  end

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations", only: [:new, :create],
  sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def add_address
    "〒" + self.postal_code + " "  + self.address + "　" + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  

  def active_for_authentication?
     super && (is_deleted == false)
  end
  
  def name
    self.last_name + self.first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  # has_many :customer, through: :cart_items
  # has_many :orders, through: :order_details
  belongs_to :genre

  def add_tax_price
      (price * 1.10).floor
      # 税込価格
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  # has_many :items, through: :order_details
  enum payment_method: { credit_card: 0, transfer: 1}
 # enum status: { waiting: 0, confirmation: 1, production: 2, preparation: 3, send: 4}


  def sum_price
      item.add_tax_price * order_details.amount
  end

  def delivery_address
      "〒" + self.postal_code + "　" + self.address + "　" + self.name
  end




end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

   def total_price
    item.add_tax_price * amount
    # 小計
   end
end

app/controllers/admin/genres_controller.rb
  class Admin::GenresController < ApplicationController
   before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end


  def create
   @genre = Genre.new(genre_params)
   @genre.save
   redirect_to '/admin/genres'
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  private
  def genre_params
   params.require(:genre).permit(:name)
  end
  end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(20)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
   before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end


  def create
   @item = Item.new(item_params)
   @item.save
   redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end




  private
  def item_params
   params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
end

app/controllers/amin/orders_controller.rb
class Amin::OrdersController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address ,:telephone_number])
   end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/amin/orders_helper.rb
module Amin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container px-2 px-sm-0">
  <h5>ジャンル編集</h5>
  <div class="row">

    <%= form_with model: @genre, url: admin_genre_path do |f| %>
    <label>ジャンル名</label>
    <%= f.text_field :name %>
     <input class="btn btn-success" type="submit" Value="変更を保存" >
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container px-2 px-sm-0">
<h5 class="col-3 text-center" style="background-color: #ddd;">ジャンル一覧・追加</h5>
<div class="row mb-5 mt-5">
<label class="col-2" >ジャンル名</label>
<%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
<%= f.text_field :name, placeholder: "ジャンル名", class:"mr-5" %>
 <%= f.submit '新規登録', class:"btn btn-success px-5"%>
<% end %>
</div>
<div class="row">

<table class="table col-4">
  <thead class="table-secondary">
    <tr>
      <th class="col-8"><div class="ml-4">ジャンル</div></th>
      <th></th>
    </tr>
  </thead>
  <% @genres.each do |genre| %>
  <tbody>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success" %></td>
    </tr>
  </tbody>

<% end %>
</table>
</div>
</div>

app/views/admin/homes/top.html.erb
<div class="container px-2 px-sm-0">

      <h5 class="col-2 text-center ml-5 mb-3" style="background-color: #ddd;">注文履歴一覧</h5>
<div class="row">
<div class="col-10 mx-auto">
<table class="table">
  <thead class="table-secondary">
    <tr>
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th>注文ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
    <tr>
      <td>
        <%= link_to admin_order_path(order.id) do %>
        <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
        <% end %>
      </td>
      <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
      <td>
        <% @amount_total = 0 %>
        <% order.order_details.each do |f| %>
        <% @amount_total += f.amount %>
        <% end %>
        <%= @amount_total %>
      </td>
      <td></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<div class="col-1 mx-auto">
<%= paginate @orders %>
</div>
</div>

app/views/admin/items/edit.html.erb
<div class="container pt-3 px-sm-0">
   <h5 class="col-2 text-center mb-5 ml-5" style="background-color: #ddd;">商品編集</h5>

  <div class="row">
　<div class="col-7 mx-auto">
     <%= form_with model: @item, url: admin_update_item_path, method: :patch, local: true do |f| %>
      <div>
     <label class="col-md-4">商品画像</label>
     <%= f.file_field :image , accept: "image/*" %></br>
    </div>

    <div>
      <label class="col-md-4">商品名</label>
      <%= f.text_field :name, placeholder: "商品名", class:"col-6" %></br>
    </div>

    <div>
      <label class="col-md-4">商品説明</label>
      <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class:"col-6" %></br>
    </div>

    <div>
      <label class="col-md-4">ジャンル</label>

      <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択してください", class:"col-6" %></br>
    </div>

    <div>
      <label class="col-md-4">税抜価格</label>
      <%= f.number_field :price, placeholder: "1000", class:"col-6" %>円</br>
    </div>

    <div>
      <label class="col-md-4">販売ステータス</label>
    <span class="col-6 pl-0">
      <%= f.radio_button :is_active, :true %>
      <%= f.label :is_active, "販売中", class:"mr-4" %>
      <%= f.radio_button :is_active, :false %>
      <%= f.label :is_active, "販売停止中" %></br>
    </span>
    </div>
<div>
<label class="col-md-5"></label>
    <%= f.submit '変更を保存', class:"btn btn-success px-5"%>
</div>
    <% end %>
</div>
</div>
</div>

app/views/admin/items/index.html.erb
<div class="container pt-3">

  <h5  class="ml-5 col-2 text-center" style="display:inline; background-color: #ddd;">商品一覧</h5>
<div class="text-right">
  <button onclick="location.href='items/new'", type="button" class="btn btn-light shadow text-dark  rounded-circle p-0 " style="width:2rem;height:2rem; margin-right: 0px;">＋</button>
</div>

<div class="row">

<div class="mx-auto col-12 mt-3">
  <table class="table">
  <thead class="table-secondary">
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name, admin_item_path(item.id) %></td>
      <td><%= item.price %></td>
      <td><%= item.genre.name %></td>
      <td><% if item.is_active == true %><span class="text-success font-weight-bold">販売中</span>
          <% else %><span class="text-secondary font-weight-bold">販売停止中</span>
          <% end %></td>
    </tr>
    <% end %>
  </tbody>
</table>



</div>
</div>
<div class="col-1 mx-auto">
<%= paginate @items %>
</div>
</div>

app/views/admin/items/new.html.erb
<div class="container pt-3 px-sm-0">
   <h5 class="col-2 text-center" style="background-color: #ddd;">商品新規登録</h5>


<div class="row">
<div class="col-7 mx-auto">
     <%= form_with model: @item, url: admin_items_new_path, method: :post, local: true do |f| %>
    <div>
     <label class="col-md-4">商品画像</label>
     <%= f.file_field :image , accept: "image/*" %></br>
    </div>

    <div>
      <label class="col-md-4">商品名</label>
      <%= f.text_field :name, placeholder: "商品名", class:"col-6" %></br>
    </div>

    <div>
      <label class="col-md-4">商品説明</label>
      <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", class:"col-6" %></br>
    </div>

    <div>
      <label class="col-md-4">ジャンル</label>

      <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択してください", class:"col-6" %></br>
    </div>

    <div>
      <label class="col-md-4">税抜価格</label>
      <%= f.number_field :price, placeholder: "1000", class:"col-6" %>円</br>
    </div>

    <div>
      <label class="col-md-4">販売ステータス</label>
    <span class="col-6 pl-0">
      <%= f.radio_button :is_active, :true %>
      <%= f.label :is_active, "販売中", class:"mr-4" %>
      <%= f.radio_button :is_active, :false %>
      <%= f.label :is_active, "販売停止中" %></br>
    </span>
    </div>
<div>
<label class="col-md-5"></label>
    <%= f.submit '新規登録', class:"btn btn-success px-5"%>
</div>
    <% end %>
</div>
</div>
</div>

app/views/admin/items/show.html.erb
<div class="container px-2 px-sm-0">
   <h5 class="col-2 text-center ml-5" style="background-color: #ddd;">商品詳細</h5>
  <div class="row ml-5 mt-5">
    <div class="col-4">
      <%= image_tag @item.image, class:"img-fluid h-75" %>
    </div>
    <div class="col-7">
     <div><label class="col-md-3">商品名</label><%= @item.name%></div>
     <div><label class="col-md-3">商品説明</label><%= @item.introduction %></div>
     <div><label class="col-md-3">ジャンル</label><%= @item.genre.name %></div>
     <div><label class="col-md-3">税込価格</br>(税抜価格)</label><%= @item.add_tax_price.to_s(:dalimited) %>(<%= @item.price %>)円</div>
     <div><label class="col-md-3">販売ステータス</label><span class="text-success font-weight-bold"><%= @item.is_active ? '販売中' : '売り切れ' %></span></div>
     <div><label class="col-md-2"></label><%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-success px-4 mt-4" %></div>
    </div>
  </div>
</div>