config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'order_details/update'
  end
  namespace :admin do
   resources :orders, only: [:show, :update]
  end
  namespace :admin do
   resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end
  namespace :admin do
    resources :items, except: [:destroy, :update, :create]
    patch 'items/:id' => 'items#update', as: 'update_item'
    post 'items/new' => 'items#create'
  end
  namespace :admin do
   patch 'order_detail/:id' => 'order_detail#update'
  end

  namespace :admin do
   root to: "homes#top"
  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }




  devise_scope :public do
    root to: "public/homes#top"
    get 'about' => 'public/homes#about', as: 'about'
    resources :addresses, only: [:index, :edit, :create, :destroy], module: 'public'
    patch 'addresses/:id/edit' => 'public/addresses#update'
    get 'orders/complete' => 'public/orders#complete'
    resources :orders, only: [:new, :index, :create, :show], module: 'public'
    post 'orders/confirm' => 'public/orders#confirm'
    delete 'cart_items' => 'public/cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create, :destroy_all], module: 'public'
    resources :items, only: [:index, :show], module: 'public'
    get 'customers/show' => 'public/customers#show'
    get 'customers/edit' => 'public/customers#edit'
    patch 'customers' => 'public/customers#update'
    get 'customers/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'
  end

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations", only: [:new, :create],
  sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def add_address
    "〒" + self.postal_code + " "  + self.address + "　" + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  

  def active_for_authentication?
     super && (is_deleted == false)
  end
  
  def name
    self.last_name + self.first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  # has_many :customer, through: :cart_items
  # has_many :orders, through: :order_details
  belongs_to :genre

  def add_tax_price
      (price * 1.10).floor
      # 税込価格
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  # has_many :items, through: :order_details
  enum payment_method: { credit_card: 0, transfer: 1}
 # enum status: { waiting: 0, confirmation: 1, production: 2, preparation: 3, send: 4}


  def sum_price
      item.add_tax_price * order_details.amount
  end

  def delivery_address
      "〒" + self.postal_code + "　" + self.address + "　" + self.name
  end




end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

   def total_price
    item.add_tax_price * amount
    # 小計
   end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(20)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
   before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end


  def create
   @item = Item.new(item_params)
   @item.save
   redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end




  private
  def item_params
   params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address ,:telephone_number])
   end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/amin/orders_helper.rb
module Amin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-#FFE4E1 bg-#FFE4E1">

      <a class="navbar-brand p-3 h-25" href="/"><%= image_tag('log.png') %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

      <ul class="navbar-nav ml-auto">
      <% if admin_signed_in? %>
      <li class="nav-item btn btn-outline-secondary "><%= link_to "商品一覧", admin_items_path, method: :get, class: "text-dark" %>

      </li>
      <li class="nav-item btn btn-outline-secondary "><%= link_to "会員一覧", admin_customers_path, method: :get, class: "text-dark" %>
      </li>
      <li class="nav-item btn btn-outline-secondary "><%= link_to "注文履歴一覧", admin_root_path, method: :get, class: "text-dark" %>
      </li>
      <li class="nav-item btn btn-outline-secondary "><%= link_to "ジャンル一覧", admin_genres_path, method: :get, class: "text-dark" %>
      </li>
       <li class="nav-item btn btn-outline-secondary "><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "text-dark" %>
      </li>
      <% elsif customer_signed_in? %>
       <li class="nav-item btn btn-outline-secondary "><%= link_to "マイページ",  customers_show_path, method: :get, class: "text-dark" %>
      </li>
       <li class="nav-item btn btn-outline-secondary "><%= link_to "商品一覧", items_path, method: :get, class: "text-dark" %>
      </li>
       <li class="nav-item btn btn-outline-secondary "><%= link_to "カート", cart_items_path, class: "text-dark" %>
      </li>
       <li class="nav-item btn btn-outline-secondary "><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "text-dark" %>
      </li>
      <% else %>
       <li class="nav-item btn btn-outline-secondary "><%= link_to "About", about_path, method: :get, class: "text-dark" %>
      </li>
       <li class="nav-item btn btn-outline-secondary "><%= link_to "商品一覧", items_path, method: :get, class: "text-dark" %>
      </li>
       <li class="nav-item btn btn-outline-secondary "><%= link_to "新規登録", new_customer_registration_path, method: :get, class: "text-dark" %>
      </li>
       <li class="nav-item btn btn-outline-secondary "><%= link_to "ログイン", new_customer_session_path, method: :get, class: "text-dark" %>
      </li>
      <% end %>
      </ul>
       </div>
       </nav>
       </div>





      </header>
      <main class="pb-5">
    <%= yield %>
    </main>
    <footer>
     <div class="container">
      <div class="row"></div>
     </div>
    </footer>
  </body>

</html>